### ISSUE TITLE
Improvements to (W)CGI server

### ISSUE THREAD

**Issue by misalcedo** [misalcedo/tortuga#116]
The CGI protocol is a great way to map HTTP requests to system processes (environment variables, stdin, stdout, stderr and arguments). Using the same protocol we can map HTTP requests to WASI invocations.

```[tasklist]
### Tasks
- [ ] Recommendations for servers and example scripts
- [ ] Security considerations
- [ ] Add support for content encodings and prevent the script from changing headers necessary for communicating correctly with the client
- [ ] Add support for HTTPS scheme and expose the scheme to the script
- [ ] Non-Parsed Header script support
- [ ] Validate and improve URI encoding support and query param parsing
- [ ] Allow running CGI scripts from anywhere in the document root directory.
- [ ] Handle the PATH and PWD variables correctly for WCGI
- [ ] Handle non-UTF-8 header values
```

## Documentation
- [CGI RFC](https://www.rfc-editor.org/rfc/rfc3875.html)
- [Cloudflare Worker Request Limits](https://developers.cloudflare.com/workers/platform/limits/)
- [Original HTTP/1.1 RFC](https://www.rfc-editor.org/rfc/rfc2616.html)
